### ISSUE TITLE
 No module named 'lib.knn.knn_pytorch._knn_pytorch'  

### ISSUE THREAD

**Issue by GaoHuaZhang** [hygxy/ma_densefusion#4]
when i run  ./experiments/scripts/train_poseownnet.sh.Can you tell me what to do? I don't know this very well～thank you!
`Traceback (most recent call last):
  File "./tools/train.py", line 19, in <module>
    from lib.loss import Loss
  File "/home/theone/ma_densefusion/lib/loss.py", line 9, in <module>
    from lib.knn.__init__ import KNearestNeighbor
  File "/home/theone/ma_densefusion/lib/knn/__init__.py", line 7, in <module>
    from lib.knn import knn_pytorch as knn_pytorch
  File "/home/theone/ma_densefusion/lib/knn/knn_pytorch/__init__.py", line 3, in <module>
    from ._knn_pytorch import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'lib.knn.knn_pytorch._knn_pytorch'
`

**Comment by WinglokWong616** [comment]
hi, did you solve this? Would you be so kind to share your solution?
